export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const SEND_NEW_EVENT_REQUEST_SUCCESS = 'SEND_NEW_EVENT_REQUEST_SUCCESS';
export const SEND_NEW_EVENT_REQUEST_FAILURE = 'SEND_NEW_EVENT_REQUEST_FAILURE';
export const LOAD_EVENT_REQUESTS_SUCCESS = 'LOAD_EVENT_REQUESTS_SUCCESS';
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const ADD_NEW_CLIENT_SUCCESS = 'ADD_NEW_CLIENT_SUCCESS';
